# Generated by Django 2.0.5 on 2018-10-10 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_userprofile_permission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='sex',
            new_name='gender',
        ),
    ]
