# Generated by Django 2.0.5 on 2018-10-22 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20181010_2147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ('country',), 'verbose_name_plural': 'UserProfiles'},
        ),
    ]
