# Generated by Django 2.0.8 on 2018-11-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20181022_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.CharField(default='None', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='userPhone',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
