# Generated by Django 2.0.8 on 2018-11-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20181116_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='userPhone',
            field=models.CharField(default='None', max_length=30),
        ),
    ]
